project : 
  name: quickstart-aws-biotech-blueprint-cdk 
  owner: quickstart-eng@amazon.com
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
tests:
  default:
    template: ./cdk.out/AwsBiotechBlueprint.template.json
    regions:
    - us-east-1
    - us-west-2
    - eu-west-1
